# Generated by Django 3.1 on 2020-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocDod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoC', models.CharField(max_length=100)),
                ('DoD', models.CharField(max_length=100)),
                ('timeStamp', models.CharField(max_length=100)),
            ],
        ),
    ]
